// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prC_;

namespace prC_.Migrations
{
    [DbContext(typeof(FilmContext))]
    [Migration("20190410101209_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("prC_.Awards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Bafta");

                    b.Property<int>("FilmId");

                    b.Property<bool>("GoldenGlob");

                    b.Property<bool>("Oscar");

                    b.HasKey("Id");

                    b.HasIndex("FilmId")
                        .IsUnique();

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("prC_.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<int>("Genre");

                    b.Property<string>("Name");

                    b.Property<string>("Prod");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("prC_.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FilmId");

                    b.Property<string>("Name");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("FilmId")
                        .IsUnique();

                    b.ToTable("Studio");
                });

            modelBuilder.Entity("prC_.Awards", b =>
                {
                    b.HasOne("prC_.Film", "Film")
                        .WithOne("Awards")
                        .HasForeignKey("prC_.Awards", "FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("prC_.Studio", b =>
                {
                    b.HasOne("prC_.Film", "Film")
                        .WithOne("Studio")
                        .HasForeignKey("prC_.Studio", "FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
